const data = {
    products:[
        {
            _id:'1',
            name:'Monitor',
            category:'computer',
            image:'/images/product-1.jpg',
            price:120,
            brand:'HyperX',
            rating: 5,
            numReviews: 10,
            description: 'Made of pure grade vibranium',
        },
        {
            _id:'2',
            name:'Monitor Stand',
            category:'computer & tools',
            image:'/images/product-2.jpg',
            price:50,
            brand:'Razor',
            rating: 4,
            numReviews: 10,
            description: 'Made of pure grade vibranium',
        },
        {
            _id:'3',
            name:'Monitor Clamps',
            category:'computer',
            image:'/images/product-3.jpg',
            price:90,
            brand:'Logitech',
            rating: 4.5,
            numReviews: 10,
            description: 'Made of pure grade vibranium',
        },
        {
            _id:'4',
            name:'Monitor Grips',
            category:'computer & tools',
            image:'/images/product-4.jpg',
            price:200,
            brand:'Corsair',
            rating: 3,
            numReviews: 10,
            description: 'Made of pure grade vibranium',
        },
        {
            _id:'5',
            name:'Monitor Tools',
            category:'computer',
            image:'/images/product-5.jpg',
            price:500,
            brand:'G-Skills',
            rating: 3.5,
            numReviews: 10,
            description: 'Made of pure grade vibranium',
        },
        {
            _id:'6',
            name:'Monitor Brass',
            category:'computer',
            image:'/images/product-6.jpg',
            price:450,
            brand:'Hydro',
            rating: 4,
            numReviews: 10,
            description: 'Made of pure grade vibranium',
        },
    ],
};
export default data;